spring:
  data:
    mongodb:
      database: library
  datasource:
    initialization-mode: always
  batch:
    job:
      enabled: false
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG