spring:
  data:
    mongodb:
      database: library
      host: "mongodb"
  datasource:
    initialization-mode: always
  batch:
    job:
      enabled: false
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  file: main.log
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitInterval: 10000
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
  backends:
    booksBackend:
      baseConfig: default