INSERT INTO BOOKS (ID, TITLE,AUTHOR_ID,GENRE_ID) VALUES (1, 'book1',1,1);
INSERT INTO BOOKS (ID, TITLE,AUTHOR_ID,GENRE_ID) VALUES (2, 'book2',2,1);
INSERT INTO BOOKS (ID, TITLE,AUTHOR_ID,GENRE_ID) VALUES (3, 'book3',2,2);
INSERT INTO BOOKS (ID, TITLE,AUTHOR_ID,GENRE_ID) VALUES (4, 'book4',3,3);

INSERT INTO AUTHOR (ID,AUTHORNAME) VALUES (1,'author1');
INSERT INTO AUTHOR (ID,AUTHORNAME) VALUES (2,'author2');
INSERT INTO AUTHOR (ID,AUTHORNAME) VALUES (3,'author3');


INSERT INTO GENRE (ID,GENRETITLE) VALUES (1,'genre1');
INSERT INTO GENRE (ID,GENRETITLE) VALUES (2,'genre2');
INSERT INTO GENRE (ID,GENRETITLE) VALUES (3,'genre3');


