DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID VARCHAR(255) PRIMARY KEY, TITLE VARCHAR(255), AUTHORID VARCHAR(255), GENREID VARCHAR(255));
DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID VARCHAR(255), AUTHORNAME VARCHAR(255));
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID VARCHAR(255),GENRETITLE VARCHAR(255));
