DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID INT PRIMARY KEY, TITLE VARCHAR(255), AUTHOR_ID INT, GENRE_ID INT);
DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID INT PRIMARY KEY, AUTHORNAME VARCHAR(255));
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID INT PRIMARY KEY,GENRETITLE VARCHAR(255));
