DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID INT PRIMARY KEY, TITLE VARCHAR(255), AUTHOR VARCHAR(255), GENRE VARCHAR(255));
DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(NAME VARCHAR(255));
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(TITLE VARCHAR(255));
